# Generated by Django 2.2.6 on 2019-10-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conclution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclude', models.CharField(max_length=500)),
                ('pict', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Depict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=500)),
            ],
        ),
    ]
